### ISSUE TITLE
Support restricting the search to only part of the file tree within a repo.

### ISSUE THREAD

**Issue by austinletson** [LennyTaelman/SorryDB#95]
The specifics here are not fleshed out yet.

Here is also a relevant thread on Zulip: [#SorryDB development > Ignoring repos and paths](https://leanprover.zulipchat.com/#narrow/channel/491104-SorryDB-development/topic/Ignoring.20repos.20and.20paths) where the following `ignore.toml` is proposed:

```toml
# takes a long time on `lake build` and inconsistent version upgrade
[[ignore]]
repo = "opencompl/lean-mlir"

[[ignore]]
repo = "leanprover-community/mathlib4"
paths = ["MathlibTest/"] # lots of false positives in the test folder
```
